Hw18.1
skayKatya/CypressKate pull request #3
Opened 2024-07-11 17:26 UTC by skayKatya

2024-07-11 19:34 UTC, sttaran requested changes

2024-07-11 19:34 UTC, sttaran commented on cypress/e2e/HW/HW18.1.cy.js
> +        welcomePageSteps.enterUserInfoWithoutRepeatedPassword()
you have to pass data into a method otherwise it is a blackbox

2024-07-11 19:34 UTC, sttaran commented on cypress/e2e/HW/HW18.1.cy.js
> +        welcomePage.getsignupLastName().click()
you can use focus() instead of click()

2024-07-17 14:46 UTC, merged

2024-07-17 14:53 UTC, skayKatya commented on cypress/e2e/HW/HW18.1.cy.js
> +        welcomePageSteps.enterUserInfoWithoutRepeatedPassword()
ok
поняв приняв, але невже метод коли ми створюємо окемо  папку steps наприклад в папці support і там описуємо все що нам потрібно зробить для цього методу (н-д регістрація на сторінці) не є гарним?

просто твій варіант коли пишеться змінна спочатку а потім метод де вказується аргумент типу наглядніший, а Паша навпаки сказав що краще окремо папку степс і там все описувать....

мені просто цікаво бест практіс на проекті як то зазвичай роблять